[package]
name = "comb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combinations = "0.1.0"
crossbeam = "0.8.2"
itertools = "0.11.0"
rayon = "1.7.0"
